name: Full Stack Checks

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  backend:
    name: FastAPI Backend Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements-dev.txt
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pytest
        run: pytest

  frontend:
    name: Next.js Frontend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/web
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: app/web/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test:unit
      - name: E2E tests
        env:
          SKIP_API_PROXY: '1'
        run: npm run test:e2e
